---
# tasks file for nginx
- name: Install Nginx
  yum:
      name: nginx # Does this live in EPEL?  Maybe need that repo installed.
      state: present
      update_cache: true
  notify:
      - Start Nginx
- name: Pull Chiglug Nginx config
  git:
      repo: https://github.com/chicagolug/chicagolug-nginx.git
      dest: /etc/nginx
